selenium:
  grid:
    enabled: true
    host: http://localhost:4444
  browser: CHROME
  browserOptions:
    acceptInsecureCerts: false
    credentialsEnableService: false
    passwordManagerLeakDetection: false
    startMaximized: true